kleaf: fix -Wmissing-prototypes errors
Add headers for missing prototypes and tag static functions on multiple
ddk examples to fix several -Wmissing-prototypes issues such as:

  ddk_library/libfoo/foo.c:24:6: error: no previous prototype for function 'foo' [-Werror,-Wmissing-prototypes]
     24 | void foo(void) {}
        |      ^

Fixes: 3a33769174d0 ("kleaf: Add DDK examples.")
Change-Id: I8e8a7c80f3fedcf55a409aa05f75e399da2c85e5
Signed-off-by: Carlos Llamas <cmllamas@google.com>